// Code generated by counterfeiter. DO NOT EDIT.
package commandfakes

import (
	"sync"

	"github.com/ablease/zinn/command"
)

type FakeMapChestsClient struct {
	MapChestsStub        func() ([]string, error)
	mapChestsMutex       sync.RWMutex
	mapChestsArgsForCall []struct {
	}
	mapChestsReturns struct {
		result1 []string
		result2 error
	}
	mapChestsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMapChestsClient) MapChests() ([]string, error) {
	fake.mapChestsMutex.Lock()
	ret, specificReturn := fake.mapChestsReturnsOnCall[len(fake.mapChestsArgsForCall)]
	fake.mapChestsArgsForCall = append(fake.mapChestsArgsForCall, struct {
	}{})
	stub := fake.MapChestsStub
	fakeReturns := fake.mapChestsReturns
	fake.recordInvocation("MapChests", []interface{}{})
	fake.mapChestsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMapChestsClient) MapChestsCallCount() int {
	fake.mapChestsMutex.RLock()
	defer fake.mapChestsMutex.RUnlock()
	return len(fake.mapChestsArgsForCall)
}

func (fake *FakeMapChestsClient) MapChestsCalls(stub func() ([]string, error)) {
	fake.mapChestsMutex.Lock()
	defer fake.mapChestsMutex.Unlock()
	fake.MapChestsStub = stub
}

func (fake *FakeMapChestsClient) MapChestsReturns(result1 []string, result2 error) {
	fake.mapChestsMutex.Lock()
	defer fake.mapChestsMutex.Unlock()
	fake.MapChestsStub = nil
	fake.mapChestsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeMapChestsClient) MapChestsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.mapChestsMutex.Lock()
	defer fake.mapChestsMutex.Unlock()
	fake.MapChestsStub = nil
	if fake.mapChestsReturnsOnCall == nil {
		fake.mapChestsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.mapChestsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeMapChestsClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mapChestsMutex.RLock()
	defer fake.mapChestsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMapChestsClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ command.MapChestsClient = new(FakeMapChestsClient)
