// Code generated by counterfeiter. DO NOT EDIT.
package commandfakes

import (
	"sync"

	"github.com/ablease/zinn/command"
)

type FakeAchievementsClient struct {
	AchievementIDsStub        func() ([]int, error)
	achievementIDsMutex       sync.RWMutex
	achievementIDsArgsForCall []struct {
	}
	achievementIDsReturns struct {
		result1 []int
		result2 error
	}
	achievementIDsReturnsOnCall map[int]struct {
		result1 []int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAchievementsClient) AchievementIDs() ([]int, error) {
	fake.achievementIDsMutex.Lock()
	ret, specificReturn := fake.achievementIDsReturnsOnCall[len(fake.achievementIDsArgsForCall)]
	fake.achievementIDsArgsForCall = append(fake.achievementIDsArgsForCall, struct {
	}{})
	stub := fake.AchievementIDsStub
	fakeReturns := fake.achievementIDsReturns
	fake.recordInvocation("AchievementIDs", []interface{}{})
	fake.achievementIDsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAchievementsClient) AchievementIDsCallCount() int {
	fake.achievementIDsMutex.RLock()
	defer fake.achievementIDsMutex.RUnlock()
	return len(fake.achievementIDsArgsForCall)
}

func (fake *FakeAchievementsClient) AchievementIDsCalls(stub func() ([]int, error)) {
	fake.achievementIDsMutex.Lock()
	defer fake.achievementIDsMutex.Unlock()
	fake.AchievementIDsStub = stub
}

func (fake *FakeAchievementsClient) AchievementIDsReturns(result1 []int, result2 error) {
	fake.achievementIDsMutex.Lock()
	defer fake.achievementIDsMutex.Unlock()
	fake.AchievementIDsStub = nil
	fake.achievementIDsReturns = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakeAchievementsClient) AchievementIDsReturnsOnCall(i int, result1 []int, result2 error) {
	fake.achievementIDsMutex.Lock()
	defer fake.achievementIDsMutex.Unlock()
	fake.AchievementIDsStub = nil
	if fake.achievementIDsReturnsOnCall == nil {
		fake.achievementIDsReturnsOnCall = make(map[int]struct {
			result1 []int
			result2 error
		})
	}
	fake.achievementIDsReturnsOnCall[i] = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakeAchievementsClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.achievementIDsMutex.RLock()
	defer fake.achievementIDsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAchievementsClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ command.AchievementsClient = new(FakeAchievementsClient)
